# Generated by Django 3.0.2 on 2020-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200222_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Type',
            field=models.CharField(choices=[('EM', 'Employer'), ('CN', 'Candidate'), ('NN', 'None')], default='NN', max_length=2),
        ),
    ]
