# Generated by Django 3.0.3 on 2020-03-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200301_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='sub_date',
            field=models.DateField(null=True),
        ),
    ]
