# Generated by Django 3.0.2 on 2020-02-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200222_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=30)),
                ('website_url', models.URLField()),
                ('applications', models.ManyToManyField(to='user.Resume')),
                ('job_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
            ],
        ),
    ]
