# Generated by Django 3.0.2 on 2020-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200223_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='default.jpg', upload_to='company_logo'),
        ),
    ]
