# Generated by Django 3.0.3 on 2020-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('job_posting_limit', models.IntegerField(default=0)),
                ('resume_view_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
