# Generated by Django 3.0.3 on 2020-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='job_posted_time',
            field=models.IntegerField(default=0),
        ),
    ]
