# Generated by Django 3.0.3 on 2020-02-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='package_type',
        ),
    ]
